services:
  - type: web
    name: node-yuki
    env: node
    buildCommand: npm install
    startCommand: node app.js
    plan: free
    numInstances: 1
    envVars:
      - key: PORT
        value: "10000"
